apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-server-chart.fullname" . }}
  labels:
    {{- include "simple-server-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.svc.port }}
      targetPort: {{ .Values.metrics.svc.port }}
      protocol: TCP
      name: {{ .Values.metrics.svc.name }}
    {{- end }}
  selector:
    {{- include "simple-server-chart.selectorLabels" . | nindent 4 }}