# Default values for simple-server-chart

replicaCount: 1

image:
  repository: simple-server
  tag: 0.0.1
  pullPolicy: Never  # Cambiado a "Never" para imágenes locales

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
metrics:
  # -- Indicates whether this app will expose metrics
  enabled: true
  # -- Service configuration used for metrics
  svc:
    # -- Service port number used for metrics
    port: 8000
    # -- Service port name used for metrics
    name: metrics