
# Default values for simple-server-chart

replicaCount: 1

image:
  repository: simple-server
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
namespaceSelector:
  matchNames:
  - fastapi-app
tolerations: []

affinity: {}

# Configuración de métricas y monitoreo
metrics:
  # -- Indica si esta aplicación expondrá métricas
  enabled: true
  # -- Configuración del servicio para métricas
  svc:
    # -- Número de puerto para métricas (usar el mismo que targetPort si la app expone métricas en el mismo puerto)
    port: 8081
    # -- Nombre del puerto para métricas (DEBE SER DIFERENTE DE "http")
    name: metrics
  # -- Configuración del ServiceMonitor
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
    interval: "15s"
    scrapeTimeout: "10s"
    honorLabels: true
    additionalLabels:
      release: prometheus
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    # -- Configuración de metricRelabelings (opcional)
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: server_requests_total|healthcheck_requests_total|main_requests_total|bye_requests_total
      action: keep